#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
sleep_idle_seconds="$(modelctl get sleep-idle-seconds)"

mmproj_args=()
if [ -n "${MMPROJ_FILE:-}" ]; then
  mmproj_args=(--mmproj "$MMPROJ_FILE")
fi

EXTRA_ARGS=()
verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  EXTRA_ARGS+=(--verbose)
fi

set -x
# Adding --no-warmup to skip the model warmup phase during server startup in order
# to reduce resource usage if not needed.
exec llama-server \
  --model "$MODEL_FILE" \
  --alias "$MODEL_NAME" \
  "${mmproj_args[@]}" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  --sleep-idle-seconds "$sleep_idle_seconds" \
  "${EXTRA_ARGS[@]}" \
  "$@"
