name: nemotron-3-nano-omni
base: core24
summary: Nemotron 3 Nano Omni inference snap
description: |
  Quickly install an optimized environment for local inference with Nemotron 3 Nano Omni (often called Nemotron 3).
  
  Before you start, make sure to have the necessary drivers installed on the host:
  https://documentation.ubuntu.com/inference-snaps/how-to/install-drivers/
  
  **Install:**
  
  `sudo snap install nemotron-3-nano-omni`
  
  **Get help:**
  
  `nemotron-3-nano-omni --help`
  
  **Licensing:**
  
  The Nemotron 3 Nano model is provided by NVIDIA Corporation under the NVIDIA Open Model License:
  https://www.nvidia.com/en-us/agreements/enterprise-software/nvidia-open-model-license/
  
  The licenses of all the bundled software can be found inside the snap at `/snap/nemotron-3-nano-omni/current/usr/share/doc`.

website: https://documentation.ubuntu.com/inference-snaps
source-code: https://github.com/canonical/nemotron-3-nano-omni-snap
issues: https://github.com/canonical/inference-snaps/issues

adopt-info: version

grade: stable
confinement: strict
compression: lzo

assumes:
  - snapd2.68 # for components support

platforms:
  amd64:
  arm64:

slots:
  status:
    interface: content
    source:
      read:
        - &status-share $SNAP_DATA/share/status
  open-webui:
    interface: content
    content: open-webui-config
    source:
      read:
        - &owui-share $SNAP_DATA/share/open-webui

plugs:
  # To allow side-loading models into server (root daemon) from user home directory
  home:
    read: all

environment:
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR
  STATUS_SHARE: *status-share # Status directory shared via content interface
  OWUI_SHARE: *owui-share # Open WebUI config directory shared via content interface
  # This is to find the intel.icd file, containing the path to libigdrcl.so
  OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

hooks:
  install:
    plugs: &install-plugs
      # For hardware detection
      - hardware-observe
      - opengl
  post-refresh:
    plugs: *install-plugs

parts:
  version:
    after: [cli]
    plugin: nil
    source: . # To regenerate the git hash on every change
    build-packages:
      - jq
      - git
    override-pull: |
      # Do nothing. This significantly reduces build time when sourcing large files.
    override-build: |
      set -eo pipefail
      cli_version=$($CRAFT_STAGE/bin/modelctl version --format=json | jq .cli --raw-output)
      git_hash=$(git -C "$SNAPCRAFT_PROJECT_DIR" describe --always)
      craftctl set version="${cli_version#v}+${git_hash}"

  cli:
    source:
      - on amd64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.4/inference-snaps-cli-linux-amd64.tar.xz
      - on arm64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.4/inference-snaps-cli-linux-arm64.tar.xz
    plugin: dump
    override-build: |
      # For tab completion
      ln --symbolic ./modelctl bin/nemotron-3-nano-omni

      craftctl default

  cli-dependencies:
    plugin: nil
    stage-packages:
      - pciutils # lspci

  # Used for NVIDIA vRAM and CUDA Capability detection.
  # Only the binary is included to avoid staging libraries, which should instead be provided by the host through the opengl interface.
  cli-nvidia-smi:
    plugin: nil
    build-packages:
      - nvidia-utils-580
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/nvidia-smi $CRAFT_PART_INSTALL/usr/bin/

      license_dir=$CRAFT_PART_INSTALL/usr/share/doc/nvidia-utils-580/
      mkdir -p $license_dir
      cp /usr/share/doc/nvidia-utils-580/copyright $license_dir/

  webui:
    plugin: dump
    source: https://github.com/canonical/inference-snaps-webui/releases/download/v1.0.0/inference-snaps-webui.tar.xz
    organize:
      "*": webui/

  engines:
    source: engines
    plugin: dump
    organize:
      "*": engines/

  models:
    source: models
    plugin: dump
    organize:
      "*": models/

  runtimes:
    source: runtimes
    plugin: dump
    organize:
      "*": runtimes/

  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - jq
    organize:
      "server.sh": bin/
      "server-webui.sh": bin/
      "export-shared-configs.sh": bin/

  model-30b-a3b-reasoning-q4-k-m:
    plugin: nil
    # WARNING: "source" is commented out to improve disk use, as a side effect,
    # snapcraft will not detect changes to the source files to clear the cache and re-prime.
    # source: components/model-30b-a3b-reasoning-q4-k-m
    override-prime: |
      set +x # reduce noise

      # Bypassing the usual part lifecycle saves disk space and time when dealing with large files
      # Copy model files directly from the project into the respective component's prime directory
      source_dir="$CRAFT_PROJECT_DIR/components/model-30b-a3b-reasoning-q4-k-m"
      for i in {1..6}; do
        target_env="CRAFT_COMPONENT_MODEL_30B_A3B_REASONING_Q4_K_M_${i}_OF_6_PRIME"
        target_comp="${!target_env}"

        # Copy the gguf shard to the component directory
        cp -v "$source_dir/nemotron-3-nano-omni-30b-a3b-reasoning-fp8_v1.0-Q4_K_M-0000${i}-of-00006.gguf" "$target_comp/"
      done

  model-mmproj-30b-a3b-fp8:
    plugin: nil
    # WARNING: "source" is commented out to improve disk use, as a side effect,
    # snapcraft will not detect changes to the source files to clear the cache and re-prime.
    # source: components/model-mmproj-30b-a3b-fp8
    override-prime: |
      set +x # reduce noise

      # Bypassing the usual part lifecycle saves disk space and time when dealing with large files
      # Copy model files directly from the project into the respective component's prime directory

      source_dir="$CRAFT_PROJECT_DIR/components/model-mmproj-30b-a3b-fp8"
      target_env="CRAFT_COMPONENT_MODEL_MMPROJ_30B_A3B_FP8_PRIME"
      target_comp="${!target_env}"

      cp -v "$source_dir/mmproj-nemotron-3-nano-omni-30b-a3b-reasoning-fp8_v1.0.gguf" "$target_comp/"

  llama-cpp:
    plugin: dump
    source:
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b8893/llamacpp-amd64.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b8893/llamacpp-arm64.tar.gz
    override-build: |
      # Move license files to be included in the snap, not the component
      mkdir -p $CRAFT_PRIME/usr/share/doc/
      mv licenses $CRAFT_PRIME/usr/share/doc/llama.cpp

      craftctl default
    stage-packages:
      - libgomp1
    organize:
      "*": (component/llama-cpp)

  llama-cpp-cuda:
    plugin: dump
    source:
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b8893/llamacpp-amd64+cuda12.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b8893/llamacpp-arm64+cuda12.tar.gz
    override-build: |
      # Move license files to be included in the snap, not the component
      mkdir -p $CRAFT_PRIME/usr/share/doc/
      mv licenses $CRAFT_PRIME/usr/share/doc/llama.cpp-cuda

      craftctl default
    stage-packages:
      - libgomp1
    organize:
      "*": (component/llama-cpp-cuda)

  notice:
    plugin: nil
    source: NOTICE
    source-type: file
    override-build: |
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc
      mkdir -p $license_dir
      cp NOTICE $license_dir/
      # Add license files referenced in NOTICE
      cp $SNAPCRAFT_PROJECT_DIR/LICENSE $license_dir/
      cp $SNAPCRAFT_PROJECT_DIR/NVIDIA-Nemotron-Open-Model-License-12-12-25.pdf $license_dir/

components:
  model-30b-a3b-reasoning-q4-k-m-1-of-6: &model
    type: standard
    summary: Sharded NVIDIA Nemotron 3 Nano Omni 30B A3B Reasoning Q4_K_M
    description: Model weights for NVIDIA Nemotron 3 Nano Omni with 30B parameters and Q4_K_M quantization in GGUF format
  model-30b-a3b-reasoning-q4-k-m-2-of-6:
    <<: *model
  model-30b-a3b-reasoning-q4-k-m-3-of-6:
    <<: *model
  model-30b-a3b-reasoning-q4-k-m-4-of-6:
    <<: *model
  model-30b-a3b-reasoning-q4-k-m-5-of-6:
    <<: *model
  model-30b-a3b-reasoning-q4-k-m-6-of-6:
    <<: *model

  model-mmproj-30b-a3b-fp8:
    type: standard
    summary: NVIDIA Nemotron 3 Nano Omni 30B A3B MMPROJ
    description: Multimodal projector for Nemotron 3 Nano Omni 30B A3B in GGUF format

  llama-cpp:
    type: standard
    summary: llama.cpp using default CPU instruction sets
    description: LLM inference in C/C++

  llama-cpp-cuda:
    type: standard
    summary: llama.cpp with CUDA backend
    description: LLM inference in C/C++

apps:
  nemotron-3-nano-omni:
    command: bin/modelctl
    completer: bin/snap-completer.bash
    plugs:
      - hardware-observe
      - opengl
      - network
      - desktop # to open the browser using webui command
    environment:
      ADDITIONAL_FEATURES: chat, webui

  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - network-bind
      - hardware-observe
      - opengl
      - home
      - network

  server-webui:
    command: bin/server-webui.sh
    daemon: simple
    plugs:
      - network-bind
