#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

EXTRA_ARGS=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  EXTRA_ARGS+=(--verbose)
fi

# Adding --no-warmup to skip the model warmup phase during server startup in order to reduce resource usage if not needed.
exec llama-server \
  --model "$MODEL_FILE" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  "${EXTRA_ARGS[@]}" \
  "$@"
