#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.post-refresh"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Refresh the active engine
#
# This involves applying changes to configurations and required snap components.
# If the active engine has been removed, another engine will be auto selected.
modelctl use-engine --fix --assume-yes --fallback=cpu
